In [ ]:
import pandas as pd
# Load the cleaned data
df = pd.read_csv("../Data/cleaned_lendingclub.csv")
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,...,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,loan_default
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,10+ years,MORTGAGE,...,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N,0
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,10+ years,MORTGAGE,...,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N,0
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,10+ years,MORTGAGE,...,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N,0
3,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,3 years,MORTGAGE,...,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N,0
4,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,4 years,RENT,...,0.0,0.0,16900.0,12798.0,9400.0,4000.0,N,Cash,N,0

#ENCODING

grade-> Ordinal (A → G)->Label encode; sub_grade-> Ordinal (A1 → G5)-> Label encode or One-hot; home_ownership-> Nominal-> One-hot encode; purpose-> Nominal-> One-hot encode; verification_status-> Nominal-> One-hot encode

In [2]:
from sklearn.preprocessing import LabelEncoder

# Encode grade (A–G)
grade_order = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
df['grade'] = df['grade'].astype(pd.CategoricalDtype(categories=grade_order, ordered=True))
df['grade_encoded'] = df['grade'].cat.codes

# Encode sub_grade (A1–G5)
sub_grade_order = [f"{g}{n}" for g in grade_order for n in range(1,6)]
df['sub_grade'] = df['sub_grade'].astype(pd.CategoricalDtype(categories=sub_grade_order, ordered=True))
df['sub_grade_encoded'] = df['sub_grade'].cat.codes

One-hot Encode Nominal Categorical Columns

In [3]:
df.drop(columns=['grade', 'sub_grade'], inplace=True)

In [4]:
df[['grade_encoded', 'sub_grade_encoded']].head()
df.filter(like='home_ownership_').head(1)
df.filter(like='purpose_').head(1)
df.filter(like='verification_status_').head(1)

Empty DataFrame
Columns: []
Index: [0]

In [7]:
# See all dummy columns created
print([col for col in df.columns if 'verification_status_' in col])
print([col for col in df.columns if 'home_ownership_' in col])
print([col for col in df.columns if 'purpose_' in col])

[]
[]
[]

In [8]:
# See how many rows belong to each one-hot encoded column
print("Verification Status Dummies:\n", df.filter(like='verification_status_').sum())
print("\nHome Ownership Dummies:\n", df.filter(like='home_ownership_').sum())
print("\nPurpose Dummies:\n", df.filter(like='purpose_').sum())

Verification Status Dummies:
 Series([], dtype: float64)

Home Ownership Dummies:
 Series([], dtype: float64)

Purpose Dummies:
 Series([], dtype: float64)

In [ ]:
df.isnull().sum().sort_values(ascending=False).head(10)

last_pymnt_d          611780
next_pymnt_d          611780
issue_d               611780
last_credit_pull_d    611780
term                       0
funded_amnt_inv            0
funded_amnt                0
int_rate                   0
emp_length                 0
home_ownership             0
dtype: int64